### ISSUE TITLE
Full day simulation results

### ISSUE THREAD

**Issue by ZijianHu-polyu** [marcorapelli/TuSTScenario#1]
Dear authors, 

Thanks for sharing this valuable sumo scenario! May I ask how the simulation result is generated? I cannot find the same picture in the paper. And I can only run a congestion result use the default parameters (e.g. Fig 7 in the paper).

Thanks.

**Comment by marcorapelli** [comment]
Dear Zijian Hu,
Thanks for considering TuST in your research project! This GitHub page was renovated after we decided to extend the work described in the paper _TuST: from Raw Data to Vehicular Traffic Simulation in Turin_. You now can find new results that complete the TuST mobility scenario, as shown in the _Full Day Simulation - Mesoscopic_ figure on the GitHub page.
Methodology and results of the new stage of the project have been deeply described in a second paper we developed. We hope it will be published soon (within next months), so that we could report it on the GitHub page as well.
Thanks.
Marco Rapelli

**Comment by ZijianHu-polyu** [comment]
I got it. Thanks very much! Wish you success in your new publication.

Best,
Zijian

**Comment by marcorapelli** [comment]
Dear @ZijianHu-polyu,
if you are still interested in TuST project, I'd like to inform you that our final project description was published in IEEE Transactions on Mobile Computing journal. You can find it as M. Rapelli, C. Casetti and G. Gagliardi, "Vehicular
Traffic Simulation in the City of Turin from Raw Data," doi: 10.1109/TMC.2021.3075985
Best,
Marco Rapelli

**Comment by ZijianHu-polyu** [comment]
> Dear @ZijianHu-polyu,
> if you are still interested in TuST project, I'd like to inform you that our final project description was published in IEEE Transactions on Mobile Computing journal. You can find it as M. Rapelli, C. Casetti and G. Gagliardi, "Vehicular
> Traffic Simulation in the City of Turin from Raw Data," doi: 10.1109/TMC.2021.3075985
> Best,
> Marco Rapelli

Dear @marcorapelli,

Thank you very much! I will carefully read your final project, and thanks again for providing such a meaningful project.

Best,
Zijian
