### ISSUE TITLE
How to execute the scenario ?

### ISSUE THREAD

**Issue by sangitatukai** [marcorapelli/TuSTScenario#2]
Hi @marcorapelli 
I am a new SUMO user. Can you please tell how to execute this TUSTScenario ? I'm getting this following error with the command: sumo -c TuST.sumocfg
Loading configuration... done.
Error: invalid document structure
 In file './TuST.net.xml'
 At line/column 2/1.

I am using sumo 1.1.0

**Comment by marcorapelli** [comment]
Hi @sangitatukai,
in order to run the scenario you need to download all the construction files declared in the TuST.sumocfg file. All the files have to be saved without changing their name in the same folder.
The error you pointed out is a loading error, which means that or you didn't download all files correctly or you have problems in loading every sumo file. Try to load a generic sumo file (also an empty net) and see if you have the same problem.
See you,
Marco Rapelli

**Comment by sangitatukai** [comment]
@marcorapelli  Hi, Thanks for your reply. 
My SUMO is working fine. You mentioned that Git lfs is required to download TuSTScenario. Could you please guide me little more how to use the git - lfs. 
I have installed git and git- lfs. but when I put this command 
$git lfs track "TuSTScenario"
this error is shown :
This operation must be run in a work tree."
I am not sure how I can download TustScenario using git lfs. 
Your help will be appreciated.

**Comment by sangitatukai** [comment]
@marcorapelli  Thanks for your reply. I have used git lfs to download the file. now it is working.
